name: Build and Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Set API Key Environment Variable
      run: echo "SOLCAST_API_KEY=${{ secrets.SOLCAST_API_KEY }}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test

    - name: Upload docs for deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
